# Generated by Django 3.0 on 2019-12-10 20:15

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoSolicitud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_tipo', models.CharField(max_length=8, verbose_name='Código de solicitud')),
                ('nombre_solicitud', models.CharField(max_length=30, verbose_name='nombre de solicitud')),
                ('descripcion_tipo', models.TextField(max_length=500, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Tipo de Solicitudes',
            },
        ),
        migrations.CreateModel(
            name='solicitud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_sol', models.TextField(help_text='Ingrese alguna descripción', max_length=5000, verbose_name='Descripción')),
                ('estado', models.CharField(max_length=10, verbose_name='Estado de la solicitud')),
                ('creada', models.DateTimeField(default=datetime.datetime.now, verbose_name='Fecha de creación')),
                ('solicitante', models.CharField(blank=True, max_length=50, null=True, verbose_name='Solicitante')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solicitud.TipoSolicitud', verbose_name='Tipo de solicitud')),
            ],
            options={
                'verbose_name': 'Solicitudes registradas',
            },
        ),
    ]
