# Generated by Django 3.0 on 2019-12-10 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiposolicitud',
            name='nombre_solicitud',
            field=models.CharField(max_length=80, verbose_name='nombre de solicitud'),
        ),
    ]
