# Generated by Django 3.0 on 2019-12-11 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitud', '0002_auto_20191210_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='descripcion_sol',
            field=models.TextField(max_length=5000, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='estado',
            field=models.CharField(choices=[('creado', 'Creado'), ('en_proceso', 'En_proceso'), ('terminado', 'Terminado')], default='creado', max_length=15, verbose_name='Estado de la solicitud'),
        ),
    ]
