# Generated by Django 3.0 on 2019-12-13 00:20

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solicitud', '0003_auto_20191211_1509'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoTema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_tipotema', models.CharField(max_length=30, verbose_name='Código de tema')),
                ('nombre_tema', models.CharField(max_length=100, verbose_name='Nombre de tema')),
                ('descripcion_tipotema', models.TextField(max_length=500, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Tipo de Temas',
            },
        ),
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_tema', models.TextField(max_length=5000, verbose_name='Describe tu consulta aquí')),
                ('fechatemacreada', models.DateTimeField(default=datetime.datetime.now, verbose_name='Fecha de creación')),
                ('tipotema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solicitud.TipoTema', verbose_name='Tipo de Temas')),
            ],
            options={
                'verbose_name': 'Temas solicitados',
            },
        ),
    ]
